### ISSUE TITLE
rasa evaluate markers all --config markers.yml extracted_markers.csv >> Erroring out

### ISSUE THREAD

**Issue by pksvv** [pksvv/rasa3.0#4]
`(rasa-latest) vipul:rasa3x$ rasa evaluate markers all --config markers.yml extracted_markers.csv
`

_Traceback (most recent call last):
  File "/opt/anaconda3/envs/rasa-latest/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/cli/evaluate.py", line 94, in _run_markers_cli
    _run_markers(
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/cli/evaluate.py", line 177, in _run_markers
    markers.evaluate_trackers(
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/evaluation/marker_base.py", line 619, in evaluate_trackers
    for tracker in trackers:
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/evaluation/marker_tracker_loader.py", line 103, in load
    yield self.tracker_store.retrieve_full_tracker(sender)
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/tracker_store.py", line 219, in retrieve_full_tracker
    return self.retrieve(conversation_id)
  File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/tracker_store.py", line 368, in retrieve
    stored = self.red.get(self.key_prefix + sender_id)
TypeError: can only concatenate str (not "bytes") to str_

**Comment by pksvv** [comment]
https://rasa.com/docs/rasa/markers
